[default]
path = "/home/alientux/pCloud_local/wallpapers/archimg_cc"
duration = "10s"
sorting = "ascending"

[default.transition.hexagonalize]
# default values for hexagonalize
# steps = 50
# horizontal-hexagons = 20.0
